#ifndef QEMU_DDRAW_H
#define QEMU_DDRAW_H

enum ddraw_calls
{
    CALL_DIRECTDRAWCREATE = 0,
    CALL_DIRECTDRAWCREATEEX,
    CALL_DIRECTDRAWENUMERATEA,
    CALL_DIRECTDRAWENUMERATEEXA,
    CALL_DIRECTDRAWENUMERATEEXW,
    CALL_DIRECTDRAWENUMERATEW,
    CALL_GETSURFACEFROMDC,
};

#ifdef QEMU_DLL_GUEST

#else

extern const struct qemu_ops *qemu_ops;

#endif

#endif
