/*
 * Copyright 2017 André Hentschel
 * Copyright 2018 Stefan Dösinger for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifndef QEMU_DINPUT_H
#define QEMU_DINPUT_H

enum dinput_calls
{
    CALL_DIRECTINPUT_CREATE = 0,
    CALL_IDIRECTINPUT2AIMPL_FINDDEVICE,
    CALL_IDIRECTINPUT2WIMPL_FINDDEVICE,
    CALL_IDIRECTINPUT7AIMPL_CREATEDEVICEEX,
    CALL_IDIRECTINPUT7WIMPL_CREATEDEVICEEX,
    CALL_IDIRECTINPUT8AIMPL_ADDREF,
    CALL_IDIRECTINPUT8AIMPL_CONFIGUREDEVICES,
    CALL_IDIRECTINPUT8AIMPL_CREATEDEVICE,
    CALL_IDIRECTINPUT8AIMPL_ENUMDEVICES,
    CALL_IDIRECTINPUT8AIMPL_ENUMDEVICESBYSEMANTICS,
    CALL_IDIRECTINPUT8AIMPL_FINDDEVICE,
    CALL_IDIRECTINPUT8AIMPL_GETDEVICESTATUS,
    CALL_IDIRECTINPUT8AIMPL_INITIALIZE,
    CALL_IDIRECTINPUT8AIMPL_QUERYINTERFACE,
    CALL_IDIRECTINPUT8AIMPL_RELEASE,
    CALL_IDIRECTINPUT8AIMPL_RUNCONTROLPANEL,
    CALL_IDIRECTINPUT8WIMPL_ADDREF,
    CALL_IDIRECTINPUT8WIMPL_CONFIGUREDEVICES,
    CALL_IDIRECTINPUT8WIMPL_CREATEDEVICE,
    CALL_IDIRECTINPUT8WIMPL_ENUMDEVICES,
    CALL_IDIRECTINPUT8WIMPL_ENUMDEVICESBYSEMANTICS,
    CALL_IDIRECTINPUT8WIMPL_FINDDEVICE,
    CALL_IDIRECTINPUT8WIMPL_GETDEVICESTATUS,
    CALL_IDIRECTINPUT8WIMPL_INITIALIZE,
    CALL_IDIRECTINPUT8WIMPL_QUERYINTERFACE,
    CALL_IDIRECTINPUT8WIMPL_RELEASE,
    CALL_IDIRECTINPUT8WIMPL_RUNCONTROLPANEL,
    CALL_IDIRECTINPUTAIMPL_ADDREF,
    CALL_IDIRECTINPUTAIMPL_CREATEDEVICE,
    CALL_IDIRECTINPUTAIMPL_ENUMDEVICES,
    CALL_IDIRECTINPUTAIMPL_GETDEVICESTATUS,
    CALL_IDIRECTINPUTAIMPL_INITIALIZE,
    CALL_IDIRECTINPUTAIMPL_QUERYINTERFACE,
    CALL_IDIRECTINPUTAIMPL_RELEASE,
    CALL_IDIRECTINPUTAIMPL_RUNCONTROLPANEL,
    CALL_IDIRECTINPUTWIMPL_ADDREF,
    CALL_IDIRECTINPUTWIMPL_CREATEDEVICE,
    CALL_IDIRECTINPUTWIMPL_ENUMDEVICES,
    CALL_IDIRECTINPUTWIMPL_GETDEVICESTATUS,
    CALL_IDIRECTINPUTWIMPL_INITIALIZE,
    CALL_IDIRECTINPUTWIMPL_QUERYINTERFACE,
    CALL_IDIRECTINPUTWIMPL_RELEASE,
    CALL_IDIRECTINPUTWIMPL_RUNCONTROLPANEL,
    CALL_INIT_DLL,
#if 0
    CALL_JOYCONFIG8IMPL_ACQUIRE,
    CALL_JOYCONFIG8IMPL_ADDNEWHARDWARE,
    CALL_JOYCONFIG8IMPL_ADDREF,
    CALL_JOYCONFIG8IMPL_DELETECONFIG,
    CALL_JOYCONFIG8IMPL_DELETETYPE,
    CALL_JOYCONFIG8IMPL_ENUMTYPES,
    CALL_JOYCONFIG8IMPL_GETCONFIG,
    CALL_JOYCONFIG8IMPL_GETTYPEINFO,
    CALL_JOYCONFIG8IMPL_GETUSERVALUES,
    CALL_JOYCONFIG8IMPL_OPENAPPSTATUSKEY,
    CALL_JOYCONFIG8IMPL_OPENTYPEKEY,
    CALL_JOYCONFIG8IMPL_QUERYINTERFACE,
    CALL_JOYCONFIG8IMPL_RELEASE,
    CALL_JOYCONFIG8IMPL_SENDNOTIFY,
    CALL_JOYCONFIG8IMPL_SETCONFIG,
    CALL_JOYCONFIG8IMPL_SETCOOPERATIVELEVEL,
    CALL_JOYCONFIG8IMPL_SETTYPEINFO,
    CALL_JOYCONFIG8IMPL_SETUSERVALUES,
    CALL_JOYCONFIG8IMPL_UNACQUIRE,
#endif
};

struct qemu_dinput
{
    /* Guest fields */
    IDirectInput7A              IDirectInput7A_iface;
    IDirectInput7W              IDirectInput7W_iface;
    IDirectInput8A              IDirectInput8A_iface;
    IDirectInput8W              IDirectInput8W_iface;
    /*IDirectInputJoyConfig8      IDirectInputJoyConfig8_iface;*/

    /* Host fields */
    IDirectInput7A              *host_7a;
    IDirectInput7W              *host_7w;
    IDirectInput8A              *host_8a;
    IDirectInput8W              *host_8w;
    /*IDirectInputJoyConfig8      *host_joy_config;*/
};

#ifdef QEMU_DLL_GUEST

#else

extern const struct qemu_ops *qemu_ops;

#endif

#endif
