name: android-arm64

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: build image
      run: docker build -f Dockerfile.android -t hangover-android-build .
    - name: get apk
      run: docker run --rm hangover-android-build tar -C /root/hangover/build/wine-host/dlls/wineandroid.drv/ -cf - hangover-debug.apk | tar -xvf -
    - uses: actions/upload-artifact@v1
      with:
        name: apk
        path: hangover-debug.apk
