name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: Trass3r/setup-cpp@master
    - name: build image
      run: docker build -f Dockerfile.android -t hob .
    - name: build
      run: docker run --rm hob tar -C /root/hangover/build.android/wine-host/dlls/wineandroid.drv/ -cf - hangover-debug.apk | tar -xvf -
    - uses: actions/upload-artifact@v1
      with:
        name: apk
        path: hangover-debug.apk
